#!/bin/sh
echo "Content-type: text/plain"
echo
[ -f found-cgi.txt ] || {
#  find /usr -iregex '.*cgi\>.*'
#  find /var -iregex '.*cgi\>.*'
cat << EOF |
/usr/lib/amanda/rest-server/public
/usr/lib/backuppc/cgi-bin
/usr/lib/cgi-bin
/usr/lib/cgi-bin/apcupsd
/usr/lib/cgi-bin/cricket
/usr/lib/cgi-bin/doc-central
/usr/lib/cgi-bin/drraw
/usr/lib/cgi-bin/gwtp
/usr/lib/cgi-bin/icinga
/usr/lib/cgi-bin/iptotal
/usr/lib/cgi-bin/lg
/usr/lib/cgi-bin/lightsquid
/usr/lib/cgi-bin/lurker
/usr/lib/cgi-bin/mobyle
/usr/lib/cgi-bin/nagios4
/usr/lib/cgi-bin/nut
/usr/lib/cgi-bin/oarapi
/usr/lib/cgi-bin/openguides
/usr/lib/cgi-bin/sympa
/usr/lib/cgit
/usr/lib/cups/cgi-bin
/usr/lib/gitano/bin
/usr/lib/gridsite/cgi-bin
/usr/lib/iipimage-server
/usr/lib/python2.7/dist-packages/Pyblosxom/data
/usr/lib/python2.7/dist-packages/trac/web/templates
/usr/lib/swish-e
/usr/lib/trinityrnaseq/Analysis/DifferentialExpression
/usr/lib/viewvc/cgi-bin
/usr/lib/w3m/cgi-bin
/usr/lib/x86_64-linux-gnu/cgi-bin
/usr/lib/xymon/server/bin
/usr/share/backuppc/cgi-bin
/usr/share/backuppc/lib
/usr/share/chalow
/usr/share/chemical-structures
/usr/share/cricket
/usr/share/cricket/util
/usr/share/doc/collectd-core/examples
/usr/share/doc/collectd-core/examples/collection3/bin
/usr/share/doc/digitemp/rrdb
/usr/share/doc/fwlogwatch/examples
/usr/share/doc/htdig-doc/examples/ewswrap
/usr/share/doc/libapache2-mod-auth-tkt/examples/cgi
/usr/share/doc/libatombus-perl/examples/public
/usr/share/doc/libauthen-captcha-perl/examples
/usr/share/doc/libbusiness-tax-vat-validation-perl/examples
/usr/share/doc/libcgi-application-perl/examples/Mailform
/usr/share/doc/libcgi-application-plugin-actiondispatch-perl/examples
/usr/share/doc/libcgi-application-plugin-authentication-perl/examples
/usr/share/doc/libcgi-application-plugin-viewcode-perl/examples
/usr/share/doc/libcgi-pm-perl/examples
/usr/share/doc/libcgi-uploader-perl/examples/friends_photos
/usr/share/doc/libchatbot-eliza-perl/examples
/usr/share/doc/libdbd-odbc-perl/examples
/usr/share/doc/libdbd-sybase-perl/examples
/usr/share/doc/libdbix-fulltextsearch-perl/examples
/usr/share/doc/libelixirfm-perl/examples/cgi/elixir
/usr/share/doc/libfcgi-async-perl/examples
/usr/share/doc/libgedcom-perl/examples
/usr/share/doc/libhtml-mason-perl-doc/examples
/usr/share/doc/libhtml-template-dumper-perl/examples
/usr/share/doc/libimager-perl/examples
/usr/share/doc/libinline-java-perl/examples/cgi
/usr/share/doc/liblemonldap-ng-manager-perl/examples
/usr/share/doc/liblemonldap-ng-portal-perl/examples
/usr/share/doc/libmath-geometry-voronoi-perl/examples
/usr/share/doc/libmyproxy-dev/extras
/usr/share/doc/libnet-async-fastcgi-perl/examples
/usr/share/doc/libnet-oauth2-perl/examples/psgi
/usr/share/doc/libnet-oauth-perl/examples
/usr/share/doc/libnetsds-perl/examples
/usr/share/doc/libpod-index-perl/examples
/usr/share/doc/libsoap-lite-perl/examples/forms
/usr/share/doc/libsoap-lite-perl/examples/server
/usr/share/doc/libsoap-lite-perl/examples/XMLRPC
/usr/share/doc/libsvg-perl/examples
/usr/share/doc/libweb-simple-perl/examples/bloggery
/usr/share/doc/libweb-simple-perl/examples/dispatchex
/usr/share/doc/libweb-simple-perl/examples/golf
/usr/share/doc/libweb-simple-perl/examples/hello-world
/usr/share/doc/libwww-nicovideo-download-perl/examples
/usr/share/doc/lua-cgi/launchers
/usr/share/doc/lua-orbit/songs
/usr/share/doc/ludevit/examples/www-simple
/usr/share/doc/mercurial-common/examples
/usr/share/doc/mrtg/examples/mrtgindex.cgi
/usr/share/doc/popularity-contest/examples/cgi-bin
/usr/share/doc/python-kid/examples/cgi
/usr/share/doc/python-mechanize/examples/forms
/usr/share/doc/python-mod-pywebsocket/examples
/usr/share/doc/python-pdfminer/examples
/usr/share/doc/rman/examples
/usr/share/doc/rrdtool/examples
/usr/share/doc/ruby-gettext/examples/cgi
/usr/share/doc/ruby-grack/examples
/usr/share/doc/ruby-locale/examples/cgi
/usr/share/doc/ruby-openid/examples/rails_openid/public
/usr/share/doc/sac/examples
/usr/share/doc/samhain/examples
/usr/share/doc/sputnik/sample-config
/usr/share/doc/swish-e/examples
/usr/share/doc/tilestache/examples
/usr/share/doc/w3m/examples/Bonus
/usr/share/doc/wiliki/examples
/usr/share/expeyes-web/cgi-bin
/usr/share/gitweb
/usr/share/global/gtags
/usr/share/go-1.11/src/net/http/cgi/testdata
/usr/share/haci/cgi-bin
/usr/share/hiki
/usr/share/hiki/misc/hikifarm
/usr/share/hiki/misc/plugin/attach
/usr/share/kannel/contrib
/usr/share/lemonldap-ng/manager/htdocs
/usr/share/lemonldap-ng/portal/htdocs
/usr/share/mailgraph
/usr/share/mfscgi
/usr/share/moin/server
/usr/share/newlisp/util
/usr/share/oar/oar-web-status
/usr/share/ogamesim-www
/usr/share/perl5/auto/share/dist/Dancer2/skel/public
/usr/share/radicale
/usr/share/request-tracker4/libexec
/usr/share/routino/www
/usr/share/rtpg-www
/usr/share/rtpg-www/htdocs
/usr/share/sinfo
/usr/share/sisu/conf/cgi-bin
/usr/share/smokeping
/usr/share/tdiary
/usr/share/torrus/bin
/usr/share/weblogin
/usr/share/wml/contrib
/var/lib/monitorix/www/cgi
/var/lib/whiteboard
/var/lib/wims/public_html
/usr/lib/cgi-bin/dacs
/usr/lib/cgi-bin/doc-central
/usr/lib/cgi-bin/drraw
/usr/lib/cgi-bin/gbrowse
/usr/lib/cgi-bin/lightsquid
/usr/lib/cgi-bin/mailman
/usr/lib/cgi-bin/man
/usr/lib/cgi-bin/mobyle
/usr/lib/cgi-bin/omega
/usr/lib/cgi-bin/openguides
/usr/lib/cgi-bin/pks
/usr/lib/cgi-bin/samba
/usr/lib/cgi-bin/sugarplum
/usr/lib/cgi-bin/w3c-markup-validator
/usr/lib/erlang/lib/inets-7.0.5/examples/server_root/cgi-bin
/usr/lib/viewvc/cgi-bin
/usr/lib/w3m/cgi-bin
/usr/lib/x86_64-linux-gnu/cgi-bin
/usr/lib/xymon/cgi-bin
/usr/share/backuppc/cgi-bin
/var/www/cgi-bin
/var/cgi-bin
/var/www/apache2/cgi-bin
/var/www/html/cgi-bin
/var/www/html/cgi-enabled
/var/www/html/cgi-test
/usr/local/apache2/cgi-bin
/usr/local/apache2/htdocs/cgi-bin
/usr/share/perl5/CGI/examples
/usr/local/awstats-7.8/wwwroot/cgi-bin/
/usr/local/lsws/DEFAULT/cgi-bin
/usr/local/lsws/fcgi-bin
/usr/local/lsws/admin/fcgi-bin
/var/www/html/munin/cgi
/var/softaculous/mt/
EOF
  while read D; do
    ls -l "$D" && echo " $D"
  done

cat << EOF |
/usr/bin
/usr/sbin
/usr/share/doc/cyrus-doc/contrib/cyrus-graphtools.1.0/cgi-bin
/usr/share/doc/icinga-cgi-bin
/usr/share/doc/libfcgi-bin
/usr/share/doc/libsoap-wsdl-perl/examples/cgi-bin
/usr/share/doc/pythoncard-doc/samples/webserver/html/cgi-bin
/usr/share/doc/yaws-doc/examples/www/cgi-bin
/usr/share/planet-venus/cgi-bin
/usr/share/samizdat/cgi-bin
EOF
  while read D; do
    ls -l "$D"/*cgi* && echo " $D"
  done
} 2>/dev/null > found-cgi.txt
cat found-cgi.txt
